/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TimeUtils */

#ifndef _Included_TimeUtils
#define _Included_TimeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TimeUtils
 * Method:    getProcessTimes
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_TimeUtils_getProcessTimes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
